import * as T from 'three';
import { canvasTexture } from './assets.js';
export class Effects{
  constructor(scene){
    this.particles=[];this.capacity=1400;this.cursor=0;this.scene=scene;this.waves=[];
    const map=canvasTexture(64,64,c=>{const g=c.createRadialGradient(32,32,0,32,32,32);g.addColorStop(0,'#fff');g.addColorStop(.2,'rgba(255,255,255,.8)');g.addColorStop(1,'rgba(255,255,255,0)');c.fillStyle=g;c.fillRect(0,0,64,64);});
    this.geo=new T.BufferGeometry();this.positions=new Float32Array(this.capacity*3);this.colors=new Float32Array(this.capacity*3);this.sizes=new Float32Array(this.capacity);
    this.geo.setAttribute('position',new T.BufferAttribute(this.positions,3));this.geo.setAttribute('color',new T.BufferAttribute(this.colors,3));this.geo.setAttribute('size',new T.BufferAttribute(this.sizes,1));
    this.mat=new T.ShaderMaterial({uniforms:{map:{value:map},pixelRatio:{value:Math.min(window.devicePixelRatio,1.5)}},vertexShader:'attribute float size; varying vec3 vColor; uniform float pixelRatio; void main(){vColor=color; vec4 p=modelViewMatrix*vec4(position,1.);gl_PointSize=min(180.,size*450.*pixelRatio/max(1.,-p.z));gl_Position=projectionMatrix*p;}',fragmentShader:'uniform sampler2D map; varying vec3 vColor; void main(){gl_FragColor=vec4(vColor,texture2D(map,gl_PointCoord).a*.7);}',transparent:true,depthWrite:false,vertexColors:true,blending:T.AdditiveBlending});
    this.mesh=new T.Points(this.geo,this.mat);this.mesh.frustumCulled=false;scene.add(this.mesh);
    this.smoke=[];this.smokeCursor=0;this.smokePositions=new Float32Array(120*3).fill(-1000);const sg=new T.BufferGeometry();sg.setAttribute('position',new T.BufferAttribute(this.smokePositions,3));this.smokeMesh=new T.Points(sg,new T.PointsMaterial({map,color:0x7d8994,size:1.7,transparent:true,opacity:.2,depthWrite:false}));this.smokeMesh.frustumCulled=false;scene.add(this.smokeMesh);
  }
  emit(position,velocity,color,size=.5,life=.5){const i=this.cursor++%this.capacity;this.particles[i]={p:new T.Vector3().copy(position),v:new T.Vector3().copy(velocity),c:new T.Color(color),size,life,maxLife:life};}
  smokeTrail(position){this.smoke[this.smokeCursor++%120]={p:new T.Vector3().copy(position),life:.8};}
  burst(position,color,count=180,power=25){for(let i=0;i<count;i++){const v=new T.Vector3(Math.random()-.5,Math.random()-.3,Math.random()-.5).normalize().multiplyScalar(power*(.2+Math.random()));this.emit(position,v,color,.3+Math.random()*1.1,.8+Math.random()*1.5);}}
  goal(position,color){for(let i=0;i<3;i++){const mesh=new T.Mesh(new T.TorusGeometry(1,.015,6,96),new T.MeshBasicMaterial({color,transparent:true,opacity:1,depthWrite:false,blending:T.AdditiveBlending}));mesh.position.copy(position);mesh.rotation.x=i===0?Math.PI/2:i===1?.3:-.3;this.scene.add(mesh);this.waves.push({mesh,age:-i*.1});}}
  update(dt){for(let i=0;i<120;i++){const p=this.smoke[i];if(!p||p.life<=0){this.smokePositions.set([-1000,-1000,-1000],i*3);continue;}p.life-=dt;p.p.y+=dt*.7;this.smokePositions.set(p.p.toArray(),i*3);}this.smokeMesh.geometry.attributes.position.needsUpdate=true;for(let i=0;i<this.capacity;i++){const p=this.particles[i];if(!p||p.life<=0){this.sizes[i]=0;continue;}p.life-=dt;p.v.multiplyScalar(Math.exp(-dt*.8));p.p.addScaledVector(p.v,dt);const alpha=Math.max(0,p.life/p.maxLife);this.positions.set(p.p.toArray(),i*3);this.colors.set(p.c.clone().multiplyScalar(alpha).toArray(),i*3);this.sizes[i]=p.size*alpha;}for(const attr of Object.values(this.geo.attributes))attr.needsUpdate=true;this.waves=this.waves.filter(w=>{w.age+=dt;w.mesh.scale.setScalar(1+Math.max(0,w.age)*42);w.mesh.material.opacity=Math.max(0,1-w.age/1.3);if(w.age>1.3){this.scene.remove(w.mesh);w.mesh.geometry.dispose();w.mesh.material.dispose();return false;}return true;});}
}
export class AudioSystem{
  constructor(){this.muted=false;this.ctx=null;}
  start(){if(this.ctx){this.ctx.resume();return;}this.ctx=new AudioContext();this.master=this.ctx.createGain();this.master.gain.value=.17;this.master.connect(this.ctx.destination);this.engine=this.ctx.createOscillator();this.engine.type='sawtooth';this.engineGain=this.ctx.createGain();this.engineGain.gain.value=0;const filter=this.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=230;this.engine.connect(filter);filter.connect(this.engineGain);this.engineGain.connect(this.master);this.engine.start();}
  tone(frequency,duration,volume=.4,type='sine'){if(!this.ctx||this.muted)return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(frequency,t);o.frequency.exponentialRampToValueAtTime(frequency*.55,t+duration);g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(this.master);o.start();o.stop(t+duration);}
  goal(){[220,330,440,660].forEach((f,i)=>setTimeout(()=>this.tone(f,.5,.5,'triangle'),i*120));}
  update(speed,boost,paused){if(!this.ctx)return;this.master.gain.setTargetAtTime(this.muted?0:.17,this.ctx.currentTime,.1);this.engine.frequency.setTargetAtTime(38+speed*3,this.ctx.currentTime,.08);this.engineGain.gain.setTargetAtTime(paused?0:boost?.13:.025+speed*.0015,this.ctx.currentTime,.08);}
}
